### ISSUE TITLE
快捷键拦截问题

### ISSUE THREAD

**Issue by oahong** [linuxdeepin/default-gsettings#1]
在打包dde的过程中，发行，如果没有安装 deepin-screenshot
下面的快捷键设定
screenshot-window=['<Alt>Print','/usr/bin/deepin-screenshot -w']
会拦截键盘的w输入。

**Comment by jouyouyun** [comment]
@oahong 这是哪里的？2014.3 里面的？

**Comment by jouyouyun** [comment]
@fasheng override 不是全部移到 deepin-desktop-schemas 里面了吗？
这个仓库还有用吗？

**Comment by fasheng** [comment]
之前漏掉了, 一会就把这个仓库归档到 https://github.com/martyr-deepin
关于这个 issue 则移步 https://github.com/linuxdeepin/dde-daemon/issues/10.

**Comment by oahong** [comment]
2015版本有这个问题。
